# Setup
title: Omnia Lab
tagline: "&#129516;"
description: "Omics and Multilevel Integrative Analysis Laboratory."
url: https://omnia-lab-uc.github.io
baseurl: /
paginate: 5
permalink: pretty

# About/contact
author:
  name: Tomas Gonzalez Zarzar
  url:
  email: tgonza@uc.cl

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y

include:
  - _pages
