# Setup
title: Omnia Lab
tagline: "Omics and Multilevel Integrative Analysis Laboratory"
logo: "/public/favicon.ico"
description: "Omics and Multilevel Integrative Analysis Laboratory"
url: https://omnia-lab-uc.github.io
baseurl: ""
paginate: 5
permalink: pretty

# About/contact
author:
  name: Dr. Tomás González Zarzar
  url:
  email: tgonza@uc.cl
  github: omnia-lab-uc
  twitter:
  google_scholar:

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y

include:
  - _pages
